name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        pytorch: [ 
          '2.6',
          '2.5', 
          '2.4', 
          '2.3', 
          '2.2.2',  # Last intel-osx compatible
          ]
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache virtual environment
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ matrix.pytorch }}-${{ hashFiles('requirements*.txt') }}
          restore-keys: ${{ runner.os }}-venv-${{ matrix.pytorch }}-

      - name: Install dependencies (only if no cache hit)
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install torch==${{ matrix.pytorch }}
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest -vvrP test.py

      - name: Run performance tests
        if: contains(github.event.head_commit.message, '[perf]')
        run: |
          . venv/bin/activate
          python test_performance.py
